# docker-compose configuration for local development

# API STACK
# =========

# Includes a container to run commands locally - a Dockerized shell
apicli:
  command: ["/app/yii","resque/work"]
  image: project_apisrc
  volumes:
    - ./api.project.de:/app
  links:
    - apinginx:API
    - mariadb:DB
    - redis:REDIS

# The php-fpm server for interpreting php code
apifpm:
  build: build/phpfpm
  volumes:
    - ./api.project.de:/app
  links:
    - mariadb:DB
    - redis:REDIS
  environment:
    YII_DEBUG: 1
    YII_ENV: dev

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php-fpm server
apinginx:
  image: schmunk42/nginx:1.7
  links:
    - apifpm:PHPFPM
  volumes:
   - ./api.project.de:/app
  ports:
    - "80"
  environment:
    VIRTUAL_HOST: ~^dev\.api\.project\..*
    NGINX_ERROR_LOG_LEVEL: 'notice'
  #command: "/app/build/stack/nginx/run.sh"

# Application runtime and data
apisrc:
  build: ./api.project.de
  command: 'tail -f /dev/null'
  volumes:
   - ./api.project.de:/app


# SHOP STACK
# ==========

shopsrc:
  build: ./shop.project.de
  command: 'tail -f /dev/null'
  volumes:
   - ./shop.project.de:/app
   # for `make docker-compose-stacks`
   - ./:/mnt

# Includes a container to run commands locally - a Dockerized shell
shopcli:
  image: project_shopsrc
  command: 'tail -f /dev/null'
  volumes:
   - ./shop.project.de:/app
  links:
    - mariadb:DB

# The php-fpm server for interpreting php code
shopfpm:
  image: phundament/php:5.6-fpm-dev
  links:
    - apinginx:API
    - mariadb:DB
  volumes:
   - ./shop.project.de:/app

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php-fpm server
shopnginx:
  image: schmunk42/nginx:1.7
  links:
    - shopfpm:PHPFPM
  volumes:
   - ./shop.project.de:/app
  ports:
    - "80"
  environment:
    VIRTUAL_HOST: ~^dev\.mcg-parts\..*
    NGINX_ERROR_LOG_LEVEL: 'notice'


# Development containers
# ======================

mariadb:
    image: tutum/mariadb:10.1
    ports:
        - "3306"
    expose:
        - "3306"
    environment:
        #MYSQL_ROOT_PASSWORD: secretroot
        #MYSQL_USER: dev
        #MYSQL_PASSWORD: dev123
        #MYSQL_DATABASE: dev-project-5
        MARIADB_PASS: secretadmin

redis:
    image: redis:3.0
    ports:
      - 6379

#adminer:
#    image: maxexcloo/adminer:latest
#    links:
#        - db
#    ports:
#        - "80"

# Mailcatcher server for catching outgoing email when not in production
#mailcatcher:
#  image: nisenabe/mailcatcher
#  ports:
#    - "25"
#    - "1080"
