# Docker compose configuration for local development
version: '2'
services:

  # The local mock version of the public haproxy router, responsible for serving the correct "web" service based on the VIRTUAL_HOST
  # locally we only have a single "web" service, nonetheless it is important to locally mimic the complete request chain
  router:
    image: dockercloud/haproxy:1.4.2
    links:
      - web
    ports:
      - "80:80"
      # Publish stats port
      - "1936"
    environment:
      TIMEOUT: connect 500, client 120000, server 120000
      # Some sort of protection for the stats endpoint (needless to say, you should use a unique secure password in production)
      STATS_AUTH: stats:n3v3rg0nnAg1v3y0uup
    # Necessary for auto-scaling using Docker-for-Mac
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
  web:
    image: nginx:1.7
    links:
      - phphaproxy
      - phpfiles
    volumes:
      - .:/app:rw
    ports:
      - "80"
    environment:
      NGINX_ERROR_LOG_LEVEL: 'notice'
      VIRTUAL_HOST: '*.127.0.0.1.xip.io, 127.0.0.1, *._PROJECT_.build.neamlabs.com, *.ngrok.io'
      # The haproxy router is configured to respond to port 80 without ssl, thus we need to make sure that proxying to the web service's port 443 is not attempted
      # A separate haproxy and corresponding web service needs to be set up to respond to port 443 with ssl if required
      EXCLUDE_PORTS: 443
    working_dir: '/app'
    command: "/app/stack/nginx/run.sh"

  # HA Proxy for php service scaling
  phphaproxy:
    image: dockercloud/haproxy:1.5.1
    links:
      - phpha
    ports:
      - "9000"
      # Publish stats port
      - "1936"
    environment:
      MODE: tcp
      TIMEOUT: connect 500, client 120000, server 120000
      # Some sort of protection for the stats endpoint (needless to say, you should use a unique secure password in production)
      STATS_AUTH: stats:n3v3rg0nnAg1v3y0uup
    # Necessary for auto-scaling using Docker-for-Mac
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # The elastically scalable php service for interpreting php code without access to /files
  phpha:
    image: neam/dna-project-base-debian-php:1.0.0
    links:
      - mailcatcher
      - redisphpsessionhandler
      - localdb
    volumes:
      - .:/app:rw
      # Use to inspect the local tmp files directory if necessary
      # - .local-tmp-files:/local-tmp-files:rw
    ports:
      - "9000"
      - "9089" # Xdebug
    environment:
      TCP_PORTS: '9000'
      DISPLAY_PHP_ERRORS: 'off'
      LOAD_XDEBUG_EXTENSION: '0'
      XDEBUG_DEFAULT_ENABLE: 'off'
      RUNNING_LOCALLY: '1'
      HHVM: '0' # 1 = Use HHVM instead of the default PHP interpreter
      PHP_PACKAGE_NAME_VERSION: '7.0'
    env_file:
      - .env
    working_dir: '/app'
    command: "/app/stack/php/run.sh"

  # The redis service used as the PHP session handler for all containers
  redisphpsessionhandler:
    image: redis
    ports:
     - "6379"

  # The single-node php service for interpreting php code with read-write access to user-generated files
  # (to support file uploads and other local file manipulations)
  phpfiles:
    image: neam/dna-project-base-debian-php:1.0.0
    links:
      - mailcatcher
      - redisphpsessionhandler
      - localdb
    volumes:
      - .:/app:rw
      - .files:/files:rw
    ports:
      - "9000"
      - "9089" # Xdebug
    environment:
      TCP_PORTS: '9000'
      DISPLAY_PHP_ERRORS: 'off'
      LOAD_XDEBUG_EXTENSION: '0'
      XDEBUG_DEFAULT_ENABLE: 'off'
      RUNNING_LOCALLY: '1'
      HHVM: '0' # 1 = Use HHVM instead of the default PHP interpreter
      PHP_PACKAGE_NAME_VERSION: '7.0'
    env_file:
      - .env
    working_dir: '/app'
    command: "/app/stack/php/run.sh"

  # Local MySQL database server to mimic a cloud database
  localdb:
    image: mysql:5.7.11
    volumes:
      - ./stack/localdb/.db/mysql:/var/lib/mysql:rw
      - ./stack/localdb/:/stack/localdb:rw
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "local-mysql-pass"
    command: "/stack/localdb/run.sh"

  # Memcached server for serving cached contents via the nginx-memcache plugin
  #memcached:
  #  image: memcached:1.4.22
  #  ports:
  #    - "11211"

  # Mailcatcher server for catching outgoing email when not in production
  mailcatcher:
    image: nisenabe/mailcatcher
    expose:
      - "25"
    ports:
      - "1080"

  # Containers to run tester commands locally - start a shell by running stack/tester-shell.sh <flavor>
  tester-hhvm:
    image: neam/dna-project-base-debian-php:1.0.0
    links:
      - web
      - api-mock
      - localdb
    volumes:
      - .:/app:rw
      - .:/personal-unit:rw
      - .files:/files:rw
      - ../.git:/.git
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro
    environment:
      DISPLAY_PHP_ERRORS: 'off'
      LOAD_XDEBUG_EXTENSION: '1'
      XDEBUG_DEFAULT_ENABLE: 'off'
      RUNNING_LOCALLY: '1'
      HHVM: '1' # 1 = Use HHVM instead of the default PHP interpreter
    working_dir: '/app/dna/tests'
    env_file:
     - .default-local-cli-data-profile
    command: "/app/stack/php/shell.sh"

  tester-php7.0:
    image: neam/dna-project-base-debian-php:1.0.0
    links:
      - web
      - api-mock
      - localdb
    volumes:
      - .:/app:rw
      - .:/personal-unit:rw
      - .files:/files:rw
      - ../.git:/.git
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro
    environment:
      DISPLAY_PHP_ERRORS: 'off'
      LOAD_XDEBUG_EXTENSION: '1'
      XDEBUG_DEFAULT_ENABLE: 'off'
      RUNNING_LOCALLY: '1'
      HHVM: '0' # 1 = Use HHVM instead of the default PHP interpreter
      PHP_PACKAGE_NAME_VERSION: '7.0'
    working_dir: '/app/dna/tests'
    env_file:
     - .default-local-cli-data-profile
    command: "/app/stack/php/shell.sh"

  tester-php7.1:
    image: neam/dna-project-base-debian-php:1.0.0-php7.1
    links:
      - web
      - api-mock
      - localdb
    volumes:
      - .:/app:rw
      - .:/personal-unit:rw
      - .files:/files:rw
      - ../.git:/.git
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro
    environment:
      DISPLAY_PHP_ERRORS: 'off'
      LOAD_XDEBUG_EXTENSION: '0'
      XDEBUG_DEFAULT_ENABLE: 'off'
      RUNNING_LOCALLY: '1'
      HHVM: '0' # 1 = Use HHVM instead of the default PHP interpreter
      PHP_PACKAGE_NAME_VERSION: '7.1'
    working_dir: '/app/dna/tests'
    env_file:
     - .default-local-cli-data-profile
    command: "/app/stack/php/shell.sh"

  # A container to run worker/administration commands locally - start a shell by running stack/shell.sh
  shell:
    image: neam/dna-project-base-debian-php:1.0.0
    links:
      - localdb
    volumes:
      - .:/app:rw
      - .files:/files:rw
      - ../.git:/.git
      - ~/.composer:/root/.composer
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro
    environment:
      DISPLAY_PHP_ERRORS: 'off'
      LOAD_XDEBUG_EXTENSION: '1'
      XDEBUG_DEFAULT_ENABLE: 'off'
      RUNNING_LOCALLY: '1'
      HHVM: '0' # 1 = Use HHVM instead of the default PHP interpreter
      PHP_PACKAGE_NAME_VERSION: '7.0'
    working_dir: '/app'
    env_file:
     - .default-local-cli-data-profile
    command: "/app/stack/php/shell.sh"
