# Data only container that includes app source code at /app and generates
# some configuration files generated based on env vars and composer.json.
# /app is subsequently used as document root in php-fpm and nginx config
src:
  image: user/project-files:git-commit-%COMMITSHA%
  volumes:
   - /app

# Data read-write container to have a temporary file system available to stack
# containers to support file uploads and other local file manipulations
files:
  image: debian:jessie
  volumes:
   - /files

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: nginx:1.7
  links:
    - php
  volumes_from:
    - src
    - files
  ports:
    - "80"
    - "443"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
  working_dir: '/app'
  command: "/app/stack/nginx/run.sh"

# The php service for interpreting php code
php:
  image: neam/debian-php:5.6.7-fpm
  volumes_from:
    - src
    - files
  ports:
   - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'off'
  env_file:
   - %ENV_FILE_DIR%/.env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

# Selenium...

# Includes a cmd to run commands defined by env vars so that administration tasks can be run by redeploying the container
#tutumworker:
#  image: debian:jessie
#  volumes:
#   - .:/app
#  environment:
#    APP_DIR: '/app'
#    WORKER_CMD: '/bin/bash echo "Hello"'
#  command: "/app/worker/run.sh"

