# Data only container that includes app source code at /app and generates
# some configuration files generated based on env vars and composer.json.
# /app is subsequently used as document root in php-fpm and nginx config
src:
  image: tutum.co/adoveo/adoveo-web-src:git-commit-%COMMITSHA%
  volumes:
   - /app
  # Set "cluster" deploy tag to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - cluster
  # Update the service when a new version is pushed to the registry
  autoredeploy: true

# Data read-write container to have a temporary file system available to stack
# containers to support file uploads and other local file manipulations
files:
  image: neam/files-empty-data-container
  volumes:
   - /files
  # Set "cluster" deploy tag to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - cluster
  # Update the service when a new version is pushed to the registry
  autoredeploy: true

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: nginx:1.7
  links:
    - src
    - php
#    - memcached
  volumes_from:
    - src
    - files
  expose:
    - "80"
    - "443"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
    VIRTUAL_HOST: %VIRTUAL_HOST%
  command: "/app/stack/nginx/run.sh"
  # Set "cluster" deploy tag to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - cluster
  # Update the service when a new version is pushed to the registry
  autoredeploy: true
  # Container distribution among nodes
  deployment_strategy: high_availability

# The php service for interpreting php code
php:
  image: neam/dna-project-base-debian-php:5.6.7-fpm
  links:
    - src
    - mailcatcher
#    - memcached
  volumes_from:
    - src
    - files
  expose:
   - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'off'
%ENVIRONMENT_YAML%
  command: "/app/stack/php/run.sh"
  # Set "cluster" deploy tag to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - cluster
  # Update the service when a new version is pushed to the registry
  autoredeploy: true
  # Container distribution among nodes
  deployment_strategy: high_availability

# Memcached server for serving cached contents via the nginx-memcache plugin
#memcached:
#  image: memcached:1.4.22
#  ports:
#    - "11211"

# Mailcatcher server for catching outgoing email when not in production
mailcatcher:
  image: nisenabe/mailcatcher
  expose:
    - "25"
  ports:
    - "1080"
  # Set "cluster" deploy tag to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - cluster
  # Update the service when a new version is pushed to the registry
  autoredeploy: true

# Selenium...

# Includes a cmd to run commands defined by env vars so that administration tasks can be run by redeploying the service
tutumworker:
  image: neam/php-app-worker:tutum-debian-jessie
  volumes_from:
    - src
    - files
  environment:
    APP_DIR: /app
    WORKER_CMD: /bin/bash echo "Hello"
%ENVIRONMENT_YAML%
  command: "/run-worker-cmd.sh"
  # Set "cluster" deploy tag to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - cluster

# For SSH access to run worker tasks manually in the cluster
worker:
  image: neam/php-app-worker:tutum-debian-jessie
  ports:
    - "22"
  volumes_from:
    - src
    - files
  environment:
    APP_DIR: /app
    AUTHORIZED_KEYS: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzKWDevt+KE0pmpFmqBbInWHo8RSowTI2qddpjeEO0vylPVZ7BxE1qYSoA0yLN4R5LdJzE44A5DR5/Vb4ytnwbo1xewZzrdwZyC7oVnkJFYSoE9HKeZytyRoICPKcgSOzG90Db8s8RvP3pKlqavQW0nXUVeS3ydBaHtuWuUZjJsFDUwOtIK++eoMOES1phDIFqr1AGFXn2V8bhpAJHGGFbC7aCSSwZE5xo56dZJGSwDLJEn8M5zN9saktM1HIPsqw7HIN1fbqZLQGYP8cAmjIC7FOc6Xyj2rHyF7CpLW6VUxHr6Gg/mDgs1K8sVSe8gjwwogRIq7o+KK9xdW6LjvnNw== motin@Fredrik-Motins-Macbook-Pro-2014.local'
%ENVIRONMENT_YAML%
  # Set "cluster" deploy tag to ensure this container is launched inside a cluster and not on a publicly facing node)
  tags:
    - cluster
