# Data only container that includes app source code at /app and generates
# some configuration files generated based on env vars and composer.json.
# /app is subsequently used as document root in php-fpm and nginx config
src:
  image: user/project-src:git-commit-%COMMITSHA%
  volumes:
   - /app
  working_dir: '/app'

# Data read-write container to have a temporary file system available to stack
# containers to support file uploads and other local file manipulations
files:
  image: neam/files-empty-data-container
  volumes:
   - /files

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: nginx:1.7
  links:
    - src
    - php
#    - memcached
  volumes_from:
    - src
    - files
  ports:
    - "80"
    - "443"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
  working_dir: '/app'
  command: "/app/stack/nginx/run.sh"

# The php service for interpreting php code
php:
  image: neam/debian-php:5.6.7-fpm
  links:
    - src
    - mailcatcher
#    - memcached
  volumes_from:
    - src
    - files
  ports:
   - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'off'
  env_file:
   - %ENV_FILE_DIR%/.env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

