# Docker compose configuration for local development

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: nginx:1.7
  links:
    - phphaproxy
    - phpfiles
  volumes:
    - .:/app:rw
  ports:
    - "80"
    - "443"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
  working_dir: '/app'
  command: "/app/stack/nginx/run.sh"

# HA Proxy for php service scaling
phphaproxy:
  image: neam/tutum-haproxy-awaiting-prs
  links:
    - phpha
  ports:
    # Publish stats port
    - "8088" # TODO: Switch to 1936 when using latest tutum master again
  environment:
    BACKEND_PORT: 9000
    FRONTEND_PORT: 9000
    STATS_AUTH: stats:stats
    MODE: tcp

# The highly available php service for interpreting php code without access to /files
phpha:
  image: neam/debian-php:5.6.9-fpm
  links:
    - mailcatcher
    - redisphpsessionhandler
  volumes:
    - .:/app:rw
  ports:
    - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'on'
    XDEBUG_DEFAULT_ENABLE: 'off'
    RUNNING_LOCALLY: '1'
    EXCLUDE_PORTS: 22
  env_file:
    - .env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

redisphpsessionhandler:
  image: redis

# The single-node php service for interpreting php code with read-write access to user-generated files
# (to support file uploads and other local file manipulations)
phpfiles:
  image: neam/debian-php:5.6.9-fpm
  links:
    - mailcatcher
    - redisphpsessionhandler
  volumes:
    - .:/app:rw
    - .files:/files:rw
  ports:
    - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'on'
    XDEBUG_DEFAULT_ENABLE: 'off'
    RUNNING_LOCALLY: '1'
    EXCLUDE_PORTS: 22
  env_file:
    - .env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

# Mailcatcher server for catching outgoing email when not in production
mailcatcher:
  image: nisenabe/mailcatcher
  ports:
    - "25"
    - "1080"

# A container that is linked to and thus can output linked information about running containers locally
info:
  image: debian:jessie
  volumes:
    - .:/app:rw
    - .files:/files:rw
  links:
    - web
    - phphaproxy
    - phpha
    - phpfiles
  working_dir: '/app'
  command: "true"
