# Docker compose configuration for local development

# Data read-only container that includes app source code at /app and generates
# some configuration files generated based on env vars and composer.json.
# /app is subsequently used as document root in php-fpm and nginx config
src:
  image: debian:jessie
  volumes:
    - .:/app:rw # TODO: Make read-only when app is configured properly not to write to anywhere else than under /files
  working_dir: '/app'

# Data read-write container to have a temporary file system available to stack
# containers to support file uploads and other local file manipulations
files:
  image: debian:jessie
  volumes:
    - .files:/files:rw
  working_dir: '/files'

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: nginx:1.7
  links:
    - php
  volumes_from:
    - src
    - files
  ports:
    - "80"
    - "443"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'
  working_dir: '/app'
  command: "/app/stack/nginx/run.sh"

# The php service for interpreting php code
php:
  image: neam/debian-php:5.6.7-fpm
  volumes_from:
    - src
    - files
  ports:
   - "9000"
  environment:
    DISPLAY_PHP_ERRORS: 'on'
    RUNNING_LOCALLY: '1'
  env_file:
   - .env
  working_dir: '/app'
  command: "/app/stack/php/run.sh"

# A container to run builder commands locally
builder:
  #build: vendor/neam/docker-stack/base-images/web-app-builder/
  image: neam/php-app-builder
  volumes_from:
    - src
    - files
  volumes:
   - ..:/project
   - ~/.composer:/root/.composer
   - ~/.ssh:/root/.ssh:ro
  working_dir: '/project/adoveo-web'
  command: "true"

# A container to run tester commands locally
tester:
  #build: vendor/neam/docker-stack/base-images/web-app-builder/
  image: neam/php-app-tester
  links:
    - web
  volumes_from:
    - src
    - files
  working_dir: '/app'
  command: "true"

# A container to run worker/administration commands locally
worker:
  #build: vendor/neam/docker-stack/base-images/web-app-worker/
  image: neam/php-app-worker
  volumes_from:
    - src
    - files
  working_dir: '/app'
  command: "true"

# A container that is linked to and thus can output linked information about running containers locally
info:
  image: debian:jessie
  links:
    - src
    - files
    - web
    - php
  volumes_from:
    - src
    - files
  working_dir: '/app'
  command: "true"

