# Docker compose configuration for local development

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: nginx:1.7
  links:
    - fpm:PHPFPM
  volumes:
   - .:/app:rw
  ports:
    - "80"
  working_dir: '/app'
  command: "nginx -c /app/nginx.conf -g 'daemon off;'"

# The php service for interpreting php code
fpm:
  image: php:5.6-fpm
  volumes:
   - .:/app
  #expose:
  # - "9000"
  working_dir: '/app'
  #command: "/app/stack/php-fpm/run.sh"

# A container to run commands locally - a Dockerized shell
cli:
  image: php:5.6-cli
  volumes:
   - .:/app
  command: /bin/true

