#
# Local stack: phundament-eco
#
reverseproxy:
    command: "sh -c 'echo \"server_tokens off;\nclient_max_body_size 512m;\" > /etc/nginx/conf.d/my_proxy.conf; forego start -r'"
    image: jwilder/nginx-proxy
    ports:
        - 80:80
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock

db:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: CHANGE_ME_CHANGE_ME_CHANGE_ME_NOW

redis:
    image: redis