# Docker compose configuration for local development

# The nginx server for serving static files directly, cached contents via the memcached server and php files via the php service
web:
  image: schmunk42/nginx:1.7
  links:
    - php:PHPFPM
  volumes:
   - .:/app:rw
  ports:
    - "80"
  environment:
    NGINX_ERROR_LOG_LEVEL: 'notice'

# The php service for interpreting php code
php:
  image: schmunk42/php:5.6-fpm
  volumes:
   - .:/app

# A container to run commands locally - a Dockerized shell
cli:
  image: schmunk42/php:5.6-cli
  volumes:
   - .:/app
